#pragma once

#define FONT_ICON_FILE_NAME_RPG "rpgawesome.ttf"

#define ICON_MIN_RPG 0xE000
#define ICON_MAX_RPG 0xF8FF

#define ICON_RPG_ACID "\xee\xa4\x80"   // U+E900
#define ICON_RPG_ZIGZAG_LEAF "\xee\xab\xae"   // U+EAEE
#define ICON_RPG_ARCHER "\xee\xa4\x8d"   // U+E90D
#define ICON_RPG_ARCHERY_TARGET "\xee\xa4\x8e"   // U+E90E
#define ICON_RPG_ARENA "\xee\xa4\x8f"   // U+E90F
#define ICON_RPG_ARIES "\xee\xa4\x90"   // U+E910
#define ICON_RPG_ARROW_CLUSTER "\xee\xa4\x91"   // U+E911
#define ICON_RPG_ARROW_FLIGHTS "\xee\xa4\x92"   // U+E912
#define ICON_RPG_ARSON "\xee\xa4\x93"   // U+E913
#define ICON_RPG_AURA "\xee\xa4\x94"   // U+E914
#define ICON_RPG_AWARE "\xee\xa4\x95"   // U+E915
#define ICON_RPG_AXE "\xee\xa4\x97"   // U+E917
#define ICON_RPG_AXE_SWING "\xee\xa4\x96"   // U+E916
#define ICON_RPG_BALL "\xee\xa4\x98"   // U+E918
#define ICON_RPG_BARBED_ARROW "\xee\xa4\x99"   // U+E919
#define ICON_RPG_BARRIER "\xee\xa4\x9a"   // U+E91A
#define ICON_RPG_BAT_SWORD "\xee\xa4\x9b"   // U+E91B
#define ICON_RPG_BATTERED_AXE "\xee\xa4\x9c"   // U+E91C
#define ICON_RPG_BATTERIES "\xee\xa4\x9d"   // U+E91D
#define ICON_RPG_BATTERY_0 "\xee\xa4\x9e"   // U+E91E
#define ICON_RPG_BATTERY_25 "\xee\xa4\x9f"   // U+E91F
#define ICON_RPG_BATTERY_50 "\xee\xa4\xa0"   // U+E920
#define ICON_RPG_BATTERY_75 "\xee\xa4\xa1"   // U+E921
#define ICON_RPG_BATTERY_100 "\xee\xa4\xa2"   // U+E922
#define ICON_RPG_BATTERY_BLACK "\xee\xa4\xa3"   // U+E923
#define ICON_RPG_BATTERY_NEGATIVE "\xee\xa4\xa4"   // U+E924
#define ICON_RPG_BATTERY_POSITIVE "\xee\xa4\xa5"   // U+E925
#define ICON_RPG_BATTERY_WHITE "\xee\xa4\xa6"   // U+E926
#define ICON_RPG_BATWINGS "\xee\xa4\xa7"   // U+E927
#define ICON_RPG_BEAM_WAKE "\xee\xa4\xa8"   // U+E928
#define ICON_RPG_BEAR_TRAP "\xee\xa4\xa9"   // U+E929
#define ICON_RPG_BEER "\xee\xa4\xaa"   // U+E92A
#define ICON_RPG_BEETLE "\xee\xa4\xab"   // U+E92B
#define ICON_RPG_BELL "\xee\xa4\xac"   // U+E92C
#define ICON_RPG_BIOHAZARD "\xee\xa4\xad"   // U+E92D
#define ICON_RPG_BIRD_CLAW "\xee\xa4\xae"   // U+E92E
#define ICON_RPG_BIRD_MASK "\xee\xa4\xaf"   // U+E92F
#define ICON_RPG_BLADE_BITE "\xee\xa4\xb0"   // U+E930
#define ICON_RPG_BLAST "\xee\xa4\xb1"   // U+E931
#define ICON_RPG_BLASTER "\xee\xa4\xb2"   // U+E932
#define ICON_RPG_BLEEDING_EYE "\xee\xa4\xb3"   // U+E933
#define ICON_RPG_BLEEDING_HEARTS "\xee\xa4\xb4"   // U+E934
#define ICON_RPG_BOLT_SHIELD "\xee\xa4\xb5"   // U+E935
#define ICON_RPG_BOMB_EXPLOSION "\xee\xa4\xb6"   // U+E936
#define ICON_RPG_BOMBS "\xee\xa4\xb7"   // U+E937
#define ICON_RPG_BONE_BITE "\xee\xa4\xb8"   // U+E938
#define ICON_RPG_BONE_KNIFE "\xee\xa4\xb9"   // U+E939
#define ICON_RPG_BOOK "\xee\xa4\xba"   // U+E93A
#define ICON_RPG_BOOMERANG "\xee\xa4\xbb"   // U+E93B
#define ICON_RPG_BOOT_STOMP "\xee\xa4\xbc"   // U+E93C
#define ICON_RPG_BOTTLE_VAPORS "\xee\xa4\xbd"   // U+E93D
#define ICON_RPG_BOTTLED_BOLT "\xee\xa4\xbe"   // U+E93E
#define ICON_RPG_BOTTOM_RIGHT "\xee\xa4\xbf"   // U+E93F
#define ICON_RPG_BOWIE_KNIFE "\xee\xa5\x80"   // U+E940
#define ICON_RPG_BOWLING_PIN "\xee\xa5\x81"   // U+E941
#define ICON_RPG_BRAIN_FREEZE "\xee\xa5\x82"   // U+E942
#define ICON_RPG_BRANDY_BOTTLE "\xee\xa5\x83"   // U+E943
#define ICON_RPG_BRIDGE "\xee\xa5\x84"   // U+E944
#define ICON_RPG_BROADHEAD_ARROW "\xee\xa5\x85"   // U+E945
#define ICON_RPG_BROADSWORD "\xee\xa5\x86"   // U+E946
#define ICON_RPG_BROKEN_BONE "\xee\xa5\x87"   // U+E947
#define ICON_RPG_BROKEN_BOTTLE "\xee\xa5\x88"   // U+E948
#define ICON_RPG_BROKEN_HEART "\xee\xa5\x88"   // U+E948
#define ICON_RPG_BROKEN_SHIELD "\xee\xa5\x8a"   // U+E94A
#define ICON_RPG_BROKEN_SKULL "\xee\xa5\x8b"   // U+E94B
#define ICON_RPG_BUBBLING_POTION "\xee\xa5\x8c"   // U+E94C
#define ICON_RPG_BULLETS "\xee\xa5\x8d"   // U+E94D
#define ICON_RPG_BURNING_BOOK "\xee\xa5\x8e"   // U+E94E
#define ICON_RPG_BURNING_EMBERS "\xee\xa5\x8f"   // U+E94F
#define ICON_RPG_BURNING_EYE "\xee\xa5\x90"   // U+E950
#define ICON_RPG_BURNING_METEOR "\xee\xa5\x91"   // U+E951
#define ICON_RPG_BURST_BLOB "\xee\xa5\x92"   // U+E952
#define ICON_RPG_BUTTERFLY "\xee\xa5\x93"   // U+E953
#define ICON_RPG_CAMPFIRE "\xee\xa5\x94"   // U+E954
#define ICON_RPG_CANCEL "\xee\xa5\x95"   // U+E955
#define ICON_RPG_CANCER "\xee\xa5\x96"   // U+E956
#define ICON_RPG_CANDLE "\xee\xa5\x98"   // U+E958
#define ICON_RPG_CANDLE_FIRE "\xee\xa5\x97"   // U+E957
#define ICON_RPG_CANNON_SHOT "\xee\xa5\x99"   // U+E959
#define ICON_RPG_CAPITOL "\xee\xa5\x9a"   // U+E95A
#define ICON_RPG_CAPRICORN "\xee\xa5\x9b"   // U+E95B
#define ICON_RPG_CARROT "\xee\xa5\x9c"   // U+E95C
#define ICON_RPG_CASTLE_EMBLEM "\xee\xa5\x9d"   // U+E95D
#define ICON_RPG_CASTLE_FLAG "\xee\xa5\x9e"   // U+E95E
#define ICON_RPG_CAT "\xee\xa5\x9f"   // U+E95F
#define ICON_RPG_CHAIN "\xee\xa5\xa0"   // U+E960
#define ICON_RPG_CHEESE "\xee\xa5\xa1"   // U+E961
#define ICON_RPG_CHEMICAL_ARROW "\xee\xa5\xa2"   // U+E962
#define ICON_RPG_CHESSBOARD "\xee\xa5\xa3"   // U+E963
#define ICON_RPG_CHICKEN_LEG "\xee\xa5\xa4"   // U+E964
#define ICON_RPG_CIRCLE_OF_CIRCLES "\xee\xa5\xa5"   // U+E965
#define ICON_RPG_CIRCULAR_SAW "\xee\xa5\xa6"   // U+E966
#define ICON_RPG_CIRCULAR_SHIELD "\xee\xa5\xa7"   // U+E967
#define ICON_RPG_CLOAK_AND_DAGGER "\xee\xa5\xa8"   // U+E968
#define ICON_RPG_CLOCKWORK "\xee\xa5\xa9"   // U+E969
#define ICON_RPG_CLOVER "\xee\xa5\xaa"   // U+E96A
#define ICON_RPG_CLOVERS "\xee\xa5\xac"   // U+E96C
#define ICON_RPG_CLOVERS_CARD "\xee\xa5\xab"   // U+E96B
#define ICON_RPG_CLUSTER_BOMB "\xee\xa5\xad"   // U+E96D
#define ICON_RPG_COFFEE_MUG "\xee\xa5\xae"   // U+E96E
#define ICON_RPG_COG "\xee\xa5\xb0"   // U+E970
#define ICON_RPG_COG_WHEEL "\xee\xa5\xaf"   // U+E96F
#define ICON_RPG_COLD_HEART "\xee\xa5\xb1"   // U+E971
#define ICON_RPG_COMPASS "\xee\xa5\xb2"   // U+E972
#define ICON_RPG_CORKED_TUBE "\xee\xa5\xb3"   // U+E973
#define ICON_RPG_CRAB_CLAW "\xee\xa5\xb4"   // U+E974
#define ICON_RPG_CRACKED_HELM "\xee\xa5\xb5"   // U+E975
#define ICON_RPG_CRACKED_SHIELD "\xee\xa5\xb6"   // U+E976
#define ICON_RPG_CROC_SWORD "\xee\xa5\xb7"   // U+E977
#define ICON_RPG_CROSSBOW "\xee\xa5\xb8"   // U+E978
#define ICON_RPG_CROSSED_AXES "\xee\xa5\xb9"   // U+E979
#define ICON_RPG_CROSSED_BONES "\xee\xa5\xba"   // U+E97A
#define ICON_RPG_CROSSED_PISTOLS "\xee\xa5\xbb"   // U+E97B
#define ICON_RPG_CROSSED_SABRES "\xee\xa5\xbc"   // U+E97C
#define ICON_RPG_CROSSED_SWORDS "\xee\xa5\xbd"   // U+E97D
#define ICON_RPG_CROWN "\xee\xa5\xbf"   // U+E97F
#define ICON_RPG_CROWN_OF_THORNS "\xee\xa5\xbe"   // U+E97E
#define ICON_RPG_CROWNED_HEART "\xee\xa6\x80"   // U+E980
#define ICON_RPG_CRUSH "\xee\xa6\x81"   // U+E981
#define ICON_RPG_CRYSTAL_BALL "\xee\xa6\x82"   // U+E982
#define ICON_RPG_CRYSTAL_CLUSTER "\xee\xa6\x83"   // U+E983
#define ICON_RPG_CRYSTAL_WAND "\xee\xa6\x84"   // U+E984
#define ICON_RPG_CRYSTALS "\xee\xa6\x85"   // U+E985
#define ICON_RPG_CUBES "\xee\xa6\x86"   // U+E986
#define ICON_RPG_CUT_PALM "\xee\xa6\x87"   // U+E987
#define ICON_RPG_CYCLE "\xee\xa6\x88"   // U+E988
#define ICON_RPG_DAGGERS "\xee\xa6\x89"   // U+E989
#define ICON_RPG_DAISY "\xee\xa6\x8a"   // U+E98A
#define ICON_RPG_DEAD_TREE "\xee\xa6\x8b"   // U+E98B
#define ICON_RPG_DEATH_SKULL "\xee\xa6\x8c"   // U+E98C
#define ICON_RPG_DECAPITATION "\xee\xa6\x8d"   // U+E98D
#define ICON_RPG_DEFIBRILLATE "\xee\xa6\x8e"   // U+E98E
#define ICON_RPG_DEMOLISH "\xee\xa6\x8f"   // U+E98F
#define ICON_RPG_DERVISH_SWORDS "\xee\xa6\x90"   // U+E990
#define ICON_RPG_DESERT_SKULL "\xee\xa6\x91"   // U+E991
#define ICON_RPG_DIAMOND "\xee\xa6\x92"   // U+E992
#define ICON_RPG_DIAMONDS "\xee\xa6\x94"   // U+E994
#define ICON_RPG_DIAMONDS_CARD "\xee\xa6\x93"   // U+E993
#define ICON_RPG_DICE_FIVE "\xee\xa6\x95"   // U+E995
#define ICON_RPG_DICE_FOUR "\xee\xa6\x96"   // U+E996
#define ICON_RPG_DICE_ONE "\xee\xa6\x97"   // U+E997
#define ICON_RPG_DICE_SIX "\xee\xa6\x98"   // U+E998
#define ICON_RPG_DICE_THREE "\xee\xa6\x99"   // U+E999
#define ICON_RPG_DICE_TWO "\xee\xa6\x9a"   // U+E99A
#define ICON_RPG_DINOSAUR "\xee\xa6\x9b"   // U+E99B
#define ICON_RPG_DIVERT "\xee\xa6\x9c"   // U+E99C
#define ICON_RPG_DIVING_DAGGER "\xee\xa6\x9d"   // U+E99D
#define ICON_RPG_DOUBLE_TEAM "\xee\xa6\x9e"   // U+E99E
#define ICON_RPG_DOUBLED "\xee\xa6\x9f"   // U+E99F
#define ICON_RPG_DRAGON "\xee\xa6\xa2"   // U+E9A2
#define ICON_RPG_DRAGON_BREATH "\xee\xa6\xa0"   // U+E9A0
#define ICON_RPG_DRAGON_WING "\xee\xa6\xa1"   // U+E9A1
#define ICON_RPG_DRAGONFLY "\xee\xa6\xa3"   // U+E9A3
#define ICON_RPG_DRILL "\xee\xa6\xa4"   // U+E9A4
#define ICON_RPG_DRIPPING_BLADE "\xee\xa6\xa5"   // U+E9A5
#define ICON_RPG_DRIPPING_KNIFE "\xee\xa6\xa6"   // U+E9A6
#define ICON_RPG_DRIPPING_SWORD "\xee\xa6\xa7"   // U+E9A7
#define ICON_RPG_DROPLET "\xee\xa6\xa9"   // U+E9A9
#define ICON_RPG_DROPLET_SPLASH "\xee\xa6\xa8"   // U+E9A8
#define ICON_RPG_DROPLETS "\xee\xa6\xaa"   // U+E9AA
#define ICON_RPG_DUEL "\xee\xa6\xab"   // U+E9AB
#define ICON_RPG_EGG "\xee\xa6\xad"   // U+E9AD
#define ICON_RPG_EGG_POD "\xee\xa6\xac"   // U+E9AC
#define ICON_RPG_EGGPLANT "\xee\xa6\xae"   // U+E9AE
#define ICON_RPG_EMERALD "\xee\xa6\xaf"   // U+E9AF
#define ICON_RPG_ENERGISE "\xee\xa6\xb0"   // U+E9B0
#define ICON_RPG_EXPLOSION "\xee\xa6\xb1"   // U+E9B1
#define ICON_RPG_EXPLOSIVE_MATERIALS "\xee\xa6\xb2"   // U+E9B2
#define ICON_RPG_EYE_MONSTER "\xee\xa6\xb3"   // U+E9B3
#define ICON_RPG_EYE_SHIELD "\xee\xa6\xb4"   // U+E9B4
#define ICON_RPG_EYEBALL "\xee\xa6\xb5"   // U+E9B5
#define ICON_RPG_FAIRY "\xee\xa6\xb7"   // U+E9B7
#define ICON_RPG_FAIRY_WAND "\xee\xa6\xb6"   // U+E9B6
#define ICON_RPG_FALL_DOWN "\xee\xa6\xb8"   // U+E9B8
#define ICON_RPG_FALLING "\xee\xa6\xb9"   // U+E9B9
#define ICON_RPG_FAST_SHIP "\xee\xa6\xba"   // U+E9BA
#define ICON_RPG_FEATHER_WING "\xee\xa6\xbb"   // U+E9BB
#define ICON_RPG_FEATHERED_WING "\xee\xa6\xbc"   // U+E9BC
#define ICON_RPG_FEDORA "\xee\xa6\xbd"   // U+E9BD
#define ICON_RPG_FIRE "\xee\xa7\x83"   // U+E9C3
#define ICON_RPG_FIRE_BOMB "\xee\xa6\xbe"   // U+E9BE
#define ICON_RPG_FIRE_BREATH "\xee\xa6\xbf"   // U+E9BF
#define ICON_RPG_FIRE_RING "\xee\xa7\x80"   // U+E9C0
#define ICON_RPG_FIRE_SHIELD "\xee\xa7\x81"   // U+E9C1
#define ICON_RPG_FIRE_SYMBOL "\xee\xa7\x82"   // U+E9C2
#define ICON_RPG_FIREBALL_SWORD "\xee\xa7\x84"   // U+E9C4
#define ICON_RPG_FISH "\xee\xa7\x85"   // U+E9C5
#define ICON_RPG_FIZZING_FLASK "\xee\xa7\x86"   // U+E9C6
#define ICON_RPG_FLAME_SYMBOL "\xee\xa7\x87"   // U+E9C7
#define ICON_RPG_FLAMING_ARROW "\xee\xa7\x88"   // U+E9C8
#define ICON_RPG_FLAMING_CLAW "\xee\xa7\x89"   // U+E9C9
#define ICON_RPG_FLAMING_TRIDENT "\xee\xa7\x8a"   // U+E9CA
#define ICON_RPG_FLASK "\xee\xa7\x8b"   // U+E9CB
#define ICON_RPG_FLAT_HAMMER "\xee\xa7\x8c"   // U+E9CC
#define ICON_RPG_FLOWER "\xee\xa7\x8d"   // U+E9CD
#define ICON_RPG_FLOWERS "\xee\xa7\x8e"   // U+E9CE
#define ICON_RPG_FLUFFY_SWIRL "\xee\xa7\x8f"   // U+E9CF
#define ICON_RPG_FOCUSED_LIGHTNING "\xee\xa7\x90"   // U+E9D0
#define ICON_RPG_FOOD_CHAIN "\xee\xa7\x91"   // U+E9D1
#define ICON_RPG_FOOTPRINT "\xee\xa7\x92"   // U+E9D2
#define ICON_RPG_FORGING "\xee\xa7\x93"   // U+E9D3
#define ICON_RPG_FORWARD "\xee\xa7\x94"   // U+E9D4
#define ICON_RPG_FOX "\xee\xa7\x95"   // U+E9D5
#define ICON_RPG_FROST_EMBLEM "\xee\xa7\x96"   // U+E9D6
#define ICON_RPG_FROSTFIRE "\xee\xa7\x97"   // U+E9D7
#define ICON_RPG_FROZEN_ARROW "\xee\xa7\x98"   // U+E9D8
#define ICON_RPG_GAMEPAD_CROSS "\xee\xa7\x99"   // U+E9D9
#define ICON_RPG_GAVEL "\xee\xa7\x9a"   // U+E9DA
#define ICON_RPG_GEAR_HAMMER "\xee\xa7\x9b"   // U+E9DB
#define ICON_RPG_GEAR_HEART "\xee\xa7\x9c"   // U+E9DC
#define ICON_RPG_GEARS "\xee\xa7\x9d"   // U+E9DD
#define ICON_RPG_GECKO "\xee\xa7\x9e"   // U+E9DE
#define ICON_RPG_GEM "\xee\xa7\xa0"   // U+E9E0
#define ICON_RPG_GEM_PENDANT "\xee\xa7\x9f"   // U+E9DF
#define ICON_RPG_GEMINI "\xee\xa7\xa1"   // U+E9E1
#define ICON_RPG_GLASS_HEART "\xee\xa7\xa2"   // U+E9E2
#define ICON_RPG_GLOOP "\xee\xa7\xa3"   // U+E9E3
#define ICON_RPG_GOLD_BAR "\xee\xa7\xa4"   // U+E9E4
#define ICON_RPG_GRAPPLING_HOOK "\xee\xa7\xa5"   // U+E9E5
#define ICON_RPG_GRASS "\xee\xa7\xa7"   // U+E9E7
#define ICON_RPG_GRASS_PATCH "\xee\xa7\xa6"   // U+E9E6
#define ICON_RPG_GRENADE "\xee\xa7\xa8"   // U+E9E8
#define ICON_RPG_GROUNDBREAKER "\xee\xa7\xa9"   // U+E9E9
#define ICON_RPG_GUARDED_TOWER "\xee\xa7\xaa"   // U+E9EA
#define ICON_RPG_GUILLOTINE "\xee\xa7\xab"   // U+E9EB
#define ICON_RPG_HALBERD "\xee\xa7\xac"   // U+E9EC
#define ICON_RPG_HAMMER "\xee\xa7\xae"   // U+E9EE
#define ICON_RPG_HAMMER_DROP "\xee\xa7\xad"   // U+E9ED
#define ICON_RPG_HAND "\xee\xa7\xb1"   // U+E9F1
#define ICON_RPG_HAND_EMBLEM "\xee\xa7\xaf"   // U+E9EF
#define ICON_RPG_HAND_SAW "\xee\xa7\xb0"   // U+E9F0
#define ICON_RPG_HARPOON_TRIDENT "\xee\xa7\xb2"   // U+E9F2
#define ICON_RPG_HEALTH "\xee\xa7\xb5"   // U+E9F5
#define ICON_RPG_HEALTH_DECREASE "\xee\xa7\xb3"   // U+E9F3
#define ICON_RPG_HEALTH_INCREASE "\xee\xa7\xb4"   // U+E9F4
#define ICON_RPG_HEART_BOTTLE "\xee\xa7\xb6"   // U+E9F6
#define ICON_RPG_HEART_TOWER "\xee\xa7\xb7"   // U+E9F7
#define ICON_RPG_HEARTBURN "\xee\xa7\xb8"   // U+E9F8
#define ICON_RPG_HEARTS "\xee\xa7\xba"   // U+E9FA
#define ICON_RPG_HEARTS_CARD "\xee\xa7\xb9"   // U+E9F9
#define ICON_RPG_HEAT_HAZE "\xee\xa7\xbb"   // U+E9FB
#define ICON_RPG_HEAVY_FALL "\xee\xa7\xbc"   // U+E9FC
#define ICON_RPG_HEAVY_SHIELD "\xee\xa7\xbd"   // U+E9FD
#define ICON_RPG_HELMET "\xee\xa7\xbe"   // U+E9FE
#define ICON_RPG_HELP "\xee\xa7\xbf"   // U+E9FF
#define ICON_RPG_HIVE_EMBLEM "\xee\xa8\x80"   // U+EA00
#define ICON_RPG_HOLE_LADDER "\xee\xa8\x81"   // U+EA01
#define ICON_RPG_HONEYCOMB "\xee\xa8\x82"   // U+EA02
#define ICON_RPG_HOOD "\xee\xa8\x83"   // U+EA03
#define ICON_RPG_HORN_CALL "\xee\xa8\x84"   // U+EA04
#define ICON_RPG_HORNS "\xee\xa8\x85"   // U+EA05
#define ICON_RPG_HORSESHOE "\xee\xa8\x86"   // U+EA06
#define ICON_RPG_HOSPITAL_CROSS "\xee\xa8\x87"   // U+EA07
#define ICON_RPG_HOT_SURFACE "\xee\xa8\x88"   // U+EA08
#define ICON_RPG_HOURGLASS "\xee\xa8\x89"   // U+EA09
#define ICON_RPG_HYDRA "\xee\xa8\x8b"   // U+EA0B
#define ICON_RPG_HYDRA_SHOT "\xee\xa8\x8a"   // U+EA0A
#define ICON_RPG_ICE_CUBE "\xee\xa8\x8c"   // U+EA0C
#define ICON_RPG_IMPLOSION "\xee\xa8\x8d"   // U+EA0D
#define ICON_RPG_INCENSE "\xee\xa8\x8e"   // U+EA0E
#define ICON_RPG_INSECT_JAWS "\xee\xa8\x8f"   // U+EA0F
#define ICON_RPG_INTERDICTION "\xee\xa8\x90"   // U+EA10
#define ICON_RPG_JETPACK "\xee\xa8\x91"   // U+EA11
#define ICON_RPG_JIGSAW_PIECE "\xee\xa8\x92"   // U+EA12
#define ICON_RPG_KALEIDOSCOPE "\xee\xa8\x93"   // U+EA13
#define ICON_RPG_KETTLEBELL "\xee\xa8\x94"   // U+EA14
#define ICON_RPG_KEY "\xee\xa8\x96"   // U+EA16
#define ICON_RPG_KEY_BASIC "\xee\xa8\x95"   // U+EA15
#define ICON_RPG_KITCHEN_KNIVES "\xee\xa8\x97"   // U+EA17
#define ICON_RPG_KNIFE "\xee\xa8\x99"   // U+EA19
#define ICON_RPG_KNIFE_FORK "\xee\xa8\x98"   // U+EA18
#define ICON_RPG_KNIGHT_HELMET "\xee\xa8\x9a"   // U+EA1A
#define ICON_RPG_KUNAI "\xee\xa8\x9b"   // U+EA1B
#define ICON_RPG_LANTERN_FLAME "\xee\xa8\x9c"   // U+EA1C
#define ICON_RPG_LARGE_HAMMER "\xee\xa8\x9d"   // U+EA1D
#define ICON_RPG_LASER_BLAST "\xee\xa8\x9e"   // U+EA1E
#define ICON_RPG_LASER_SITE "\xee\xa8\x9f"   // U+EA1F
#define ICON_RPG_LAVA "\xee\xa8\xa0"   // U+EA20
#define ICON_RPG_LEAF "\xee\xa8\xa1"   // U+EA21
#define ICON_RPG_LEO "\xee\xa8\xa2"   // U+EA22
#define ICON_RPG_LEVEL_FOUR "\xee\xa8\xa4"   // U+EA24
#define ICON_RPG_LEVEL_FOUR_ADVANCED "\xee\xa8\xa3"   // U+EA23
#define ICON_RPG_LEVEL_THREE "\xee\xa8\xa6"   // U+EA26
#define ICON_RPG_LEVEL_THREE_ADVANCED "\xee\xa8\xa5"   // U+EA25
#define ICON_RPG_LEVEL_TWO "\xee\xa8\xa8"   // U+EA28
#define ICON_RPG_LEVEL_TWO_ADVANCED "\xee\xa8\xa7"   // U+EA27
#define ICON_RPG_LEVER "\xee\xa8\xa9"   // U+EA29
#define ICON_RPG_LIBRA "\xee\xa8\xaa"   // U+EA2A
#define ICON_RPG_LIGHT_BULB "\xee\xa8\xab"   // U+EA2B
#define ICON_RPG_LIGHTHOUSE "\xee\xa8\xac"   // U+EA2C
#define ICON_RPG_LIGHTNING "\xee\xa8\xb1"   // U+EA31
#define ICON_RPG_LIGHTNING_BOLT "\xee\xa8\xad"   // U+EA2D
#define ICON_RPG_LIGHTNING_STORM "\xee\xa8\xae"   // U+EA2E
#define ICON_RPG_LIGHTNING_SWORD "\xee\xa8\xaf"   // U+EA2F
#define ICON_RPG_LIGHTNING_TRIO "\xee\xa8\xb0"   // U+EA30
#define ICON_RPG_LION "\xee\xa8\xb2"   // U+EA32
#define ICON_RPG_LIT_CANDELABRA "\xee\xa8\xb3"   // U+EA33
#define ICON_RPG_LOAD "\xee\xa8\xb4"   // U+EA34
#define ICON_RPG_LOCKED_FORTRESS "\xee\xa8\xb5"   // U+EA35
#define ICON_RPG_LOVE_HOWL "\xee\xa8\xb6"   // U+EA36
#define ICON_RPG_MAGGOT "\xee\xa8\xb7"   // U+EA37
#define ICON_RPG_MAGNET "\xee\xa8\xb8"   // U+EA38
#define ICON_RPG_MASS_DRIVER "\xee\xa8\xb9"   // U+EA39
#define ICON_RPG_MATCH "\xee\xa8\xba"   // U+EA3A
#define ICON_RPG_MEAT "\xee\xa8\xbc"   // U+EA3C
#define ICON_RPG_MEAT_HOOK "\xee\xa8\xbb"   // U+EA3B
#define ICON_RPG_MEDICAL_PACK "\xee\xa8\xbd"   // U+EA3D
#define ICON_RPG_METAL_GATE "\xee\xa8\xbe"   // U+EA3E
#define ICON_RPG_MICROPHONE "\xee\xa8\xbf"   // U+EA3F
#define ICON_RPG_MINE_WAGON "\xee\xa9\x80"   // U+EA40
#define ICON_RPG_MINING_DIAMONDS "\xee\xa9\x81"   // U+EA41
#define ICON_RPG_MIRROR "\xee\xa9\x82"   // U+EA42
#define ICON_RPG_MONSTER_SKULL "\xee\xa9\x83"   // U+EA43
#define ICON_RPG_MOUNTAINS "\xee\xa9\x84"   // U+EA44
#define ICON_RPG_MOON_SUN "\xee\xa9\x85"   // U+EA45
#define ICON_RPG_MP5 "\xee\xa9\x86"   // U+EA46
#define ICON_RPG_MUSCLE_FAT "\xee\xa9\x87"   // U+EA47
#define ICON_RPG_MUSCLE_UP "\xee\xa9\x88"   // U+EA48
#define ICON_RPG_MUSKET "\xee\xa9\x89"   // U+EA49
#define ICON_RPG_NAILS "\xee\xa9\x8a"   // U+EA4A
#define ICON_RPG_NODULAR "\xee\xa9\x8b"   // U+EA4B
#define ICON_RPG_NOOSE "\xee\xa9\x8c"   // U+EA4C
#define ICON_RPG_NUCLEAR "\xee\xa9\x8d"   // U+EA4D
#define ICON_RPG_OCARINA "\xee\xa9\x8e"   // U+EA4E
#define ICON_RPG_OCEAN_EMBLEM "\xee\xa9\x8f"   // U+EA4F
#define ICON_RPG_OCTOPUS "\xee\xa9\x90"   // U+EA50
#define ICON_RPG_OMEGA "\xee\xa9\x91"   // U+EA51
#define ICON_RPG_ON_TARGET "\xee\xa9\x92"   // U+EA52
#define ICON_RPG_OPHIUCHUS "\xee\xa9\x93"   // U+EA53
#define ICON_RPG_OVERHEAD "\xee\xa9\x94"   // U+EA54
#define ICON_RPG_OVERMIND "\xee\xa9\x95"   // U+EA55
#define ICON_RPG_PALM_TREE "\xee\xa9\x96"   // U+EA56
#define ICON_RPG_PAWN "\xee\xa9\x97"   // U+EA57
#define ICON_RPG_PAWPRINT "\xee\xa9\x98"   // U+EA58
#define ICON_RPG_PERSPECTIVE_DICE_FIVE "\xee\xa9\x99"   // U+EA59
#define ICON_RPG_PERSPECTIVE_DICE_FOUR "\xee\xa9\x9a"   // U+EA5A
#define ICON_RPG_PERSPECTIVE_DICE_ONE "\xee\xa9\x9b"   // U+EA5B
#define ICON_RPG_PERSPECTIVE_DICE_RANDOM "\xee\xa9\x9c"   // U+EA5C
#define ICON_RPG_PERSPECTIVE_DICE_SIX "\xee\xa9\x9e"   // U+EA5E
#define ICON_RPG_PERSPECTIVE_DICE_TWO "\xee\xa9\x9d"   // U+EA5D
#define ICON_RPG_PERSPECTIVE_DICE_THREE "\xee\xa9\x9f"   // U+EA5F
#define ICON_RPG_PILL "\xee\xa9\xa0"   // U+EA60
#define ICON_RPG_PILLS "\xee\xa9\xa1"   // U+EA61
#define ICON_RPG_PINE_TREE "\xee\xa9\xa2"   // U+EA62
#define ICON_RPG_PING_PONG "\xee\xa9\xa3"   // U+EA63
#define ICON_RPG_PISCES "\xee\xa9\xa4"   // U+EA64
#define ICON_RPG_PLAIN_DAGGER "\xee\xa9\xa5"   // U+EA65
#define ICON_RPG_PLAYER "\xee\xa9\xaf"   // U+EA6F
#define ICON_RPG_PLAYER_DESPAIR "\xee\xa9\xa6"   // U+EA66
#define ICON_RPG_PLAYER_DODGE "\xee\xa9\xa7"   // U+EA67
#define ICON_RPG_PLAYER_KING "\xee\xa9\xa8"   // U+EA68
#define ICON_RPG_PLAYER_LIFT "\xee\xa9\xa9"   // U+EA69
#define ICON_RPG_PLAYER_PAIN "\xee\xa9\xaa"   // U+EA6A
#define ICON_RPG_PLAYER_PYROMANIAC "\xee\xa9\xab"   // U+EA6B
#define ICON_RPG_PLAYER_SHOT "\xee\xa9\xac"   // U+EA6C
#define ICON_RPG_PLAYER_TELEPORT "\xee\xa9\xad"   // U+EA6D
#define ICON_RPG_PLAYER_THUNDER_STRUCK "\xee\xa9\xae"   // U+EA6E
#define ICON_RPG_PODIUM "\xee\xa9\xb0"   // U+EA70
#define ICON_RPG_POISON_CLOUD "\xee\xa9\xb1"   // U+EA71
#define ICON_RPG_POTION "\xee\xa9\xb2"   // U+EA72
#define ICON_RPG_PYRAMIDS "\xee\xa9\xb3"   // U+EA73
#define ICON_RPG_QUEEN_CROWN "\xee\xa9\xb4"   // U+EA74
#define ICON_RPG_QUILL_INK "\xee\xa9\xb5"   // U+EA75
#define ICON_RPG_RABBIT "\xee\xa9\xb6"   // U+EA76
#define ICON_RPG_RADAR_DISH "\xee\xa9\xb7"   // U+EA77
#define ICON_RPG_RADIAL_BALANCE "\xee\xa9\xb8"   // U+EA78
#define ICON_RPG_RADIOACTIVE "\xee\xa9\xb9"   // U+EA79
#define ICON_RPG_RAVEN "\xee\xa9\xba"   // U+EA7A
#define ICON_RPG_REACTOR "\xee\xa9\xbb"   // U+EA7B
#define ICON_RPG_RECYCLE "\xee\xa9\xbc"   // U+EA7C
#define ICON_RPG_REGENERATION "\xee\xa9\xbd"   // U+EA7D
#define ICON_RPG_RELIC_BLADE "\xee\xa9\xbe"   // U+EA7E
#define ICON_RPG_REPAIR "\xee\xa9\xbf"   // U+EA7F
#define ICON_RPG_REVERSE "\xee\xaa\x80"   // U+EA80
#define ICON_RPG_REVOLVER "\xee\xaa\x81"   // U+EA81
#define ICON_RPG_RIFLE "\xee\xaa\x82"   // U+EA82
#define ICON_RPG_RINGING_BELL "\xee\xaa\x83"   // U+EA83
#define ICON_RPG_ROAST_CHICKEN "\xee\xaa\x84"   // U+EA84
#define ICON_RPG_ROBOT_ARM "\xee\xaa\x85"   // U+EA85
#define ICON_RPG_ROUND_BOTTOM_FLASK "\xee\xaa\x86"   // U+EA86
#define ICON_RPG_ROUND_SHIELD "\xee\xaa\x87"   // U+EA87
#define ICON_RPG_RSS "\xee\xaa\x88"   // U+EA88
#define ICON_RPG_RUNE_STONE "\xee\xaa\x89"   // U+EA89
#define ICON_RPG_SAGITTARIUS "\xee\xaa\x8a"   // U+EA8A
#define ICON_RPG_SAPPHIRE "\xee\xaa\x8b"   // U+EA8B
#define ICON_RPG_SATELLITE "\xee\xaa\x8c"   // U+EA8C
#define ICON_RPG_SAVE "\xee\xaa\x8d"   // U+EA8D
#define ICON_RPG_SCORPIO "\xee\xaa\x8e"   // U+EA8E
#define ICON_RPG_SCROLL_UNFURLED "\xee\xaa\x8f"   // U+EA8F
#define ICON_RPG_SCYTHE "\xee\xaa\x90"   // U+EA90
#define ICON_RPG_SEA_SERPENT "\xee\xaa\x91"   // U+EA91
#define ICON_RPG_SEAGULL "\xee\xaa\x92"   // U+EA92
#define ICON_RPG_SHARK "\xee\xaa\x93"   // U+EA93
#define ICON_RPG_SHEEP "\xee\xaa\x94"   // U+EA94
#define ICON_RPG_SHERIFF "\xee\xaa\x95"   // U+EA95
#define ICON_RPG_SHIELD "\xee\xaa\x96"   // U+EA96
#define ICON_RPG_SHIP_EMBLEM "\xee\xaa\x97"   // U+EA97
#define ICON_RPG_SHOE_PRINTS "\xee\xaa\x98"   // U+EA98
#define ICON_RPG_SHOT_THROUGH_THE_HEART "\xee\xaa\x99"   // U+EA99
#define ICON_RPG_SHOTGUN_SHELL "\xee\xaa\x9a"   // U+EA9A
#define ICON_RPG_SHOVEL "\xee\xaa\x9b"   // U+EA9B
#define ICON_RPG_SHURIKEN "\xee\xaa\x9c"   // U+EA9C
#define ICON_RPG_SICKLE "\xee\xaa\x9d"   // U+EA9D
#define ICON_RPG_SIDESWIPE "\xee\xaa\x9e"   // U+EA9E
#define ICON_RPG_SITE "\xee\xaa\x9f"   // U+EA9F
#define ICON_RPG_SKULL "\xee\xaa\xa1"   // U+EAA1
#define ICON_RPG_SKULL_TROPHY "\xee\xaa\xa0"   // U+EAA0
#define ICON_RPG_SLASH_RING "\xee\xaa\xa2"   // U+EAA2
#define ICON_RPG_SMALL_FIRE "\xee\xaa\xa3"   // U+EAA3
#define ICON_RPG_SNAIL "\xee\xaa\xa4"   // U+EAA4
#define ICON_RPG_SNAKE "\xee\xaa\xa5"   // U+EAA5
#define ICON_RPG_SNORKEL "\xee\xaa\xa6"   // U+EAA6
#define ICON_RPG_SNOWFLAKE "\xee\xaa\xa7"   // U+EAA7
#define ICON_RPG_SOCCER_BALL "\xee\xaa\xa8"   // U+EAA8
#define ICON_RPG_SPADES "\xee\xaa\xaa"   // U+EAAA
#define ICON_RPG_SPADES_CARD "\xee\xaa\xa9"   // U+EAA9
#define ICON_RPG_SPAWN_NODE "\xee\xaa\xab"   // U+EAAB
#define ICON_RPG_SPEAR_HEAD "\xee\xaa\xac"   // U+EAAC
#define ICON_RPG_SPEECH_BUBBLE "\xee\xaa\xad"   // U+EAAD
#define ICON_RPG_SPEECH_BUBBLES "\xee\xaa\xae"   // U+EAAE
#define ICON_RPG_SPIDER_FACE "\xee\xaa\xaf"   // U+EAAF
#define ICON_RPG_SPIKEBALL "\xee\xaa\xb0"   // U+EAB0
#define ICON_RPG_SPIKED_MACE "\xee\xaa\xb1"   // U+EAB1
#define ICON_RPG_SPIKED_TENTACLE "\xee\xaa\xb2"   // U+EAB2
#define ICON_RPG_SPINNING_SWORD "\xee\xaa\xb3"   // U+EAB3
#define ICON_RPG_SPIRAL_SHELL "\xee\xaa\xb4"   // U+EAB4
#define ICON_RPG_SPLASH "\xee\xaa\xb5"   // U+EAB5
#define ICON_RPG_SPRAY_CAN "\xee\xaa\xb6"   // U+EAB6
#define ICON_RPG_SPROUT "\xee\xaa\xb8"   // U+EAB8
#define ICON_RPG_SPROUT_EMBLEM "\xee\xaa\xb7"   // U+EAB7
#define ICON_RPG_STOPWATCH "\xee\xaa\xb9"   // U+EAB9
#define ICON_RPG_SUCKERED_TENTACLE "\xee\xaa\xba"   // U+EABA
#define ICON_RPG_SUITS "\xee\xaa\xbb"   // U+EABB
#define ICON_RPG_SUN "\xee\xaa\xbd"   // U+EABD
#define ICON_RPG_SUN_SYMBOL "\xee\xaa\xbc"   // U+EABC
#define ICON_RPG_SUNBEAMS "\xee\xaa\xbe"   // U+EABE
#define ICON_RPG_SUPER_MUSHROOM "\xee\xaa\xbf"   // U+EABF
#define ICON_RPG_SUPERSONIC_ARROW "\xee\xab\x80"   // U+EAC0
#define ICON_RPG_SURVEILLANCE_CAMERA "\xee\xab\x81"   // U+EAC1
#define ICON_RPG_SYRINGE "\xee\xab\x82"   // U+EAC2
#define ICON_RPG_TARGET_ARROWS "\xee\xab\x83"   // U+EAC3
#define ICON_RPG_TARGET_LASER "\xee\xab\x84"   // U+EAC4
#define ICON_RPG_TARGETED "\xee\xab\x85"   // U+EAC5
#define ICON_RPG_TAURUS "\xee\xab\x86"   // U+EAC6
#define ICON_RPG_TELESCOPE "\xee\xab\x87"   // U+EAC7
#define ICON_RPG_TENTACLE "\xee\xab\x88"   // U+EAC8
#define ICON_RPG_TESLA "\xee\xab\x89"   // U+EAC9
#define ICON_RPG_THORN_ARROW "\xee\xab\x8a"   // U+EACA
#define ICON_RPG_THORNY_VINE "\xee\xab\x8b"   // U+EACB
#define ICON_RPG_THREE_KEYS "\xee\xab\x8c"   // U+EACC
#define ICON_RPG_TIC_TAC_TOE "\xee\xab\x8d"   // U+EACD
#define ICON_RPG_TOAST "\xee\xab\x8e"   // U+EACE
#define ICON_RPG_TOMBSTONE "\xee\xab\x8f"   // U+EACF
#define ICON_RPG_TOOTH "\xee\xab\x90"   // U+EAD0
#define ICON_RPG_TORCH "\xee\xab\x91"   // U+EAD1
#define ICON_RPG_TOWER "\xee\xab\x92"   // U+EAD2
#define ICON_RPG_TRAIL "\xee\xab\x93"   // U+EAD3
#define ICON_RPG_TREFOIL_LILY "\xee\xab\x94"   // U+EAD4
#define ICON_RPG_TRIDENT "\xee\xab\x95"   // U+EAD5
#define ICON_RPG_TRIFORCE "\xee\xab\x96"   // U+EAD6
#define ICON_RPG_TROPHY "\xee\xab\x97"   // U+EAD7
#define ICON_RPG_TURD "\xee\xab\x98"   // U+EAD8
#define ICON_RPG_TWO_DRAGONS "\xee\xab\x99"   // U+EAD9
#define ICON_RPG_TWO_HEARTS "\xee\xab\x9a"   // U+EADA
#define ICON_RPG_UNCERTAINTY "\xee\xab\x9b"   // U+EADB
#define ICON_RPG_UNDERHAND "\xee\xab\x9c"   // U+EADC
#define ICON_RPG_UNPLUGGED "\xee\xab\x9d"   // U+EADD
#define ICON_RPG_VASE "\xee\xab\x9e"   // U+EADE
#define ICON_RPG_VENOMOUS_SNAKE "\xee\xab\x9f"   // U+EADF
#define ICON_RPG_VEST "\xee\xab\xa0"   // U+EAE0
#define ICON_RPG_VIAL "\xee\xab\xa1"   // U+EAE1
#define ICON_RPG_VINE_WHIP "\xee\xab\xa2"   // U+EAE2
#define ICON_RPG_VIRGO "\xee\xab\xa3"   // U+EAE3
#define ICON_RPG_WATER_DROP "\xee\xab\xa4"   // U+EAE4
#define ICON_RPG_WIFI "\xee\xab\xa5"   // U+EAE5
#define ICON_RPG_WIRELESS_SIGNAL "\xee\xab\xa6"   // U+EAE6
#define ICON_RPG_WOLF_HEAD "\xee\xab\xa7"   // U+EAE7
#define ICON_RPG_WOLF_HOWL "\xee\xab\xa8"   // U+EAE8
#define ICON_RPG_WOODEN_SIGN "\xee\xab\xa9"   // U+EAE9
#define ICON_RPG_WRENCH "\xee\xab\xaa"   // U+EAEA
#define ICON_RPG_WYVERN "\xee\xab\xab"   // U+EAEB
#define ICON_RPG_X_MARK "\xee\xab\xac"   // U+EAEC
#define ICON_RPG_ZEBRA_SHIELD "\xee\xab\xad"   // U+EAED
#define ICON_RPG_ARCANE_MASK "\xee\xa4\x8c"   // U+E90C
#define ICON_RPG_AQUARIUS "\xee\xa4\x8b"   // U+E90B
#define ICON_RPG_APPLE "\xee\xa4\x8a"   // U+E90A
#define ICON_RPG_ANVIL "\xee\xa4\x89"   // U+E909
#define ICON_RPG_ANKH "\xee\xa4\x88"   // U+E908
#define ICON_RPG_ANGEL_WINGS "\xee\xa4\x87"   // U+E907
#define ICON_RPG_ANCHOR "\xee\xa4\x86"   // U+E906
#define ICON_RPG_AMMO_BAG "\xee\xa4\x85"   // U+E905
#define ICON_RPG_ALLIGATOR_CLIP "\xee\xa4\x84"   // U+E904
#define ICON_RPG_ALL_FOR_ONE "\xee\xa4\x83"   // U+E903
#define ICON_RPG_ALIEN_FIRE "\xee\xa4\x82"   // U+E902
#define ICON_RPG_ACORN "\xee\xa4\x81"   // U+E901
